services:
  # Backend API Server
  - type: web
    name: trivia-tiles-server
    env: node
    buildCommand: cd trivia-tiles/server && npm install
    startCommand: cd trivia-tiles/server && npm start
    rootDir: trivia-tiles/server
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
    
  # Frontend Static Site  
  - type: static
    name: trivia-tiles-client
    env: static
    buildCommand: cd trivia-tiles/client && npm install && npm run build
    staticPublishPath: trivia-tiles/client/out
    rootDir: trivia-tiles/client
    plan: free
    region: oregon
    branch: main
    buildFilter:
      paths:
      - trivia-tiles/client/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: trivia-tiles-server
          property: host 