name: CI/CD for Trivia Tiles (DISABLED - Using AI Agent Workflow)
    
# Disabled - All functionality moved to ai-agent-iteration.yml
# on:
#   push:
#     branches:
#       - main
#   pull_request:
    
jobs:
  build_and_test_frontend:
    runs-on: ubuntu-latest
    if: false  # Disable this workflow
    defaults:
      run:
        working-directory: trivia-tiles/client
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
    
      - name: Install frontend dependencies
        run: npm ci
    
      - name: Run frontend tests
        run: npm test
    
      - name: Build frontend
        run: npm run build